### PR TITLE
Add KeywordFilter property to AdRotator

### LINKED ISSUE #209: Complete implementing AdRotator attributes
Some attributes for the AdRotator that need to be completed:

- [ ] All Style attributes, implementing IHasStyle
- [ ] KeywordFilter

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #209

### CODE REVIEW

**Comment by hishamco** [comment]
@csharpfritz I'm not sure why the style is not been applied, so that's why the test is fail :(

**Comment by hishamco** [comment]
@csharpfritz the build is pass ;) the strange thing I realize there's a bug in `IHasStyle` properties, when I use the border once the `Style` attribute is not calculated, we need to open another issue and merge this

**Comment by csharpfritz** [comment]
Interesting discovery on the IHasStyle properties not recalculating.  I'll write up another issue for that

**Comment by csharpfritz** [comment]
Thank you for the fix!

**Pull request merged**
