### PR TITLE
Added WebColor

### LINKED ISSUE #13: Colors in markup
In Web Forms, you were able to set attribute values for colors to either a color name or to an HTML hex color representation.  In our components, you're forced in a Color object

### PR DESCRIPTION
**Pull request by Code-DJ**
Fixes #13
- Modified .gitignore to exclude macOS .files.
- Changed Color to WebColor in all razor files.
- ~~To use #hexformat color in razor, you have to use "@("#ff0000")".~~

### CODE REVIEW

**Comment by csharpfritz** [comment]
I like this fix because it gives us the flexibility we need with the Color markup on components.  

Can you add a small unit test that shows the new hex-color formatting?

**Comment by Code-DJ** [comment]
> Can you add a small unit test that shows the new hex-color formatting?

Is it okay if I change the color in one of the sample files and one of the tests or do you want me to add a new one?

Also, it is unfortunate that razor doesn't support "#hexcode". We have to use the work around of creating a string and using it like this "@("#ff0000")".

**Comment by csharpfritz** [comment]
That's GREAT to hear!  I'll merge this on-stream Monday.

Thank you for your help

**Comment by Code-DJ** [comment]
@csharpfritz I am sorry for this back and forth but here is what I am seeing:

- When I use hex for AfterBlazorServerSide//HeaderStyle.razor, HeaderStyle-BackColor="#C84630", both VSCode and command line show no errors.
- When I use hex for AfterBlazorServerSide//ComplexStyle.razor, BoderColor="#808080", both VSCode and command line show error - CS1024: Preprocessor directive expected.
- When I use hex for BlazorWebFormsComponentsTest//ComplexStyle.razor, ComplexStyle.razor BackColor="#0000ff", both VSCode and command line build show CS1024: Preprocessor directive expected.

Neither of these have anything to do with this repo and are standard razor syntax limitations. I have pushed the color changes so you can see it.

**Pull request closed without merging**
