### PR TITLE
Update AfterBlazorClientSide to 3.2 Preview 2

### PR DESCRIPTION
**Pull request by SpaceShot**
Some minor assembly name changes as detailed in this post: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available

This also required a minor using update.

Addresses #115 

Ignored the issues with building BeforeWebForms for now.

### CODE REVIEW

**Comment by csharpfritz** [comment]
We need to update the global.json in the root folder to point to 3.1.102

Also:  I get an error with a missing reference to the _framework/blazor.webasssembly.js file

**Comment by SpaceShot** [comment]
Thanks for the heads up on global.json.  Checking on the missing reference

**Comment by SpaceShot** [comment]
I moved on top of dev (as of this commit) and tested by cloning on a different machine that had never had this .NET Core SDK installed before.  Built cleanly and ran the AfterBlazorClientSide project.  Let me know your results.

I didn't have to do everything in the blog post.  Not sure if I should be concerned about that,

**Comment by csharpfritz** [comment]
Implemented version 3.2 preview 3 and cleared up the issues

**Pull request closed without merging**
