### PR TITLE
Fixed formatting in all files

### PR DESCRIPTION
**Pull request by Eilon**
Used 'dotnet format' command with a tweaked .editorConfig file to format all files.
- A small change was made to .editorConfig to work around https://github.com/dotnet/roslyn/issues/22601
- The first commit fixes everything except BeforeWebForms because 'dotnet format' can't process the legacy project
- The second commit fixed BeforeWebForms folder
- The main changes are tab consistency and namespace cleanup, but a few other minor changes were made

### CODE REVIEW

**Comment by Eilon** [comment]
More info on `dotnet format`:

* Repo is here: https://github.com/dotnet/format
* I ran the dev build by running `dotnet tool install -g dotnet-format --version 5.0.135301 --add-source https://dotnet.myget.org/F/format/api/v3/index.json`
* And the command I ran was `dotnet-format --fix-style -v diag` (I set verbosity=diagnostic to try to see what it was doing and figuring out the Roslyn issue)

**Comment by hishamco** [comment]
I suffer a lot from the formatting in this project ;)

Thanks Elion

**Comment by Eilon** [comment]
@hishamco indeed 😄 But at least `dotnet format` helps make it a lot better. Except for that weird Roslyn bug, which probably took me an hour to figure out.

**Comment by Eilon** [comment]
Added a 2nd commit that fixes the BeforeWebForms folder. You can run `dotnet format` on a "folder" instead of a "project", which is what's needed here because it can't process legacy CSPROJ files (used by WebForms).

The command I ran was: `dotnet-format -v diag -f`

**Comment by hishamco** [comment]
BTW @csharpfritz has been setup a GitHub action for that but I am not sure if it's working properly

**Comment by Eilon** [comment]
Looks like the format workflow was removed just recently: https://github.com/FritzAndFriends/BlazorWebFormsComponents/commit/3c5a63d2aad39498076ed11786920e29eeb4f7a5#diff-02d9c370a663741451423342d5869b21

**Comment by csharpfritz** [comment]
Yes, the format was not working properly as it was attempting to checkout and work with remote repositories that it didn't have access to

**Pull request merged**
