### PR TITLE
Add LinkButton control

### LINKED ISSUE #132: Create a LinkButton component
Should have identical features to the Button component, except rendering a hyperlink instead of a button tag

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #132

### CODE REVIEW

**Comment by hishamco** [comment]
I will add the docs soon

**Comment by csharpfritz** [comment]
What happens if you have the LinkButton class inherit from the Button class instead of the BaseWebFormsComponent?  You _SHOULD_ be able to re-use a lot of the same logic

**Comment by hishamco** [comment]
That's what I think of at the beginning, but WebForms controls are different, may we could introduce `IButtonControl` instead to make look exact same as WebForms controls

**Comment by hishamco** [comment]
@csharpfritz hope this looks good for you

**Comment by csharpfritz** [comment]
YAAAAAaaaas!   LOVE the code re-use on this @hishamco!

**Comment by hishamco** [comment]
Please :shipit: then I can start with `ImageButton` which is follow the same principle

**Comment by csharpfritz** [comment]
Thank you for this contribution!  Looking forward to the ImageButton

**Pull request merged**
