### PR TITLE
GridView Tests fix

### PR DESCRIPTION
**Pull request by JuViquez**
Issue #122 fixed

### CODE REVIEW

**Comment by grleachman** [comment]
Is this change to fix issue #122 ?
I'm not convinced of this change will resolve #122 in fact I am having problems recreating the issue.

Both using the watch script and my test runner within visual studio, I have not been able to generate the change-1 test failure we saw in the video with the .ToList() in place.
Even with the ToList() the test passes every time. I've even run the test runner on churn (ie it just keeps running the test) and this test passes all time.

I have seen this error only once which was on the first run of the test runner when I opened visual studio, so I have no evidence that removing ToList() actually does anything for the test.

**Comment by JuViquez** [comment]
@grleachman You are right, eliminating .ToList() does not solve the error, and actually I still don't know why that error happened in the first place, the way I solved it was by doing some changes to the ` EmptyDataText` test that you can review in the `Files changed` tab, since then I haven't run into that error again.

**Comment by csharpfritz** [comment]
I will hold off merging this until we get a solid fix for this issue

**Comment by csharpfritz** [comment]
The original GridView would sort with a PropertyDescriptorCollection.  Details at the .NET Framework source at:  https://referencesource.microsoft.com/#System.Web/UI/WebControls/GridViewColumnsGenerator.cs,33

**Comment by csharpfritz** [comment]
I have added a filter and an OrderBy to the GridViewColumnGenerator class and this MIGHT solve the problem

**Comment by grleachman** [comment]
Very interesting issue.. 
highlighting the complexity of column ordering, both implied and explicitly set as attributes.

see commit [04b42ce](https://github.com/grleachman/BlazorWebFormsComponents/commit/04b42ced6ffe599657a6e30a6a4f8ef3120f098a) where I've applied Display Attribute Ordering to the Customer Object.

The code that manages column ordering is truly mind boggling, and illustrates the breadth of resources that must have been applied to provide such feature rich product like webforms.

**Pull request merged**
