### PR TITLE
GridView DataSource should be of type object

### LINKED ISSUE #191: Investigate:  Can we simplify DataTable datasources?
Can we either wrap our components or improve the DataBinding code to detect a DataTable / DataSet and execute the AsDynamicEnumerable() extension method internally to the component?

We need to simplify the signature of the controls so that using a DataTable / DataSet **ONLY** requires the same markup or API interaction as the original control

### PR DESCRIPTION
**Pull request by hishamco**
Fix #191

### CODE REVIEW

**Comment by hishamco** [comment]
- `DataSource` return type should be of type `object`

- Call `AsDynamicEnumerable()` internally in case of DataTable

**Comment by hishamco** [comment]
@csharpfritz it's ready

**Comment by csharpfritz** [comment]
Thank you very much for your work to support DataSet and make DataTable binding easier!

**Comment by hishamco** [comment]
Anytime J. Fritz while this will help the WebForms developers ;)

**Pull request merged**
