### PR TITLE
Add OnDataBinding() to BaseWebFormsComponent

### LINKED ISSUE #216: Button DataBinding support?
The official documentation reports an OnDataBinding attribute.  What does this get wired up to, and how does it effect the button?

Please investigate

### PR DESCRIPTION
**Pull request by hishamco**
Fixed #216 and #218

### CODE REVIEW

**Comment by csharpfritz** [comment]
Looks like a merge conflict after the formatting change.

**Comment by hishamco** [comment]
I didn't realize that there's a similar event somewhere else (`BaseDataBindingComponent`) until I see the test logs ;)

**Comment by csharpfritz** [comment]
I would like to keep the DataBinding features all on the `BaseDataBindingComponent` so that its clear which components have the DataBinding features and they all get added to a component at the same time.

Perhaps we just change the base class for the components we need to add DataBinding features to

**Comment by hishamco** [comment]
> Perhaps we just change the base class for the components we need to add DataBinding features to

What if we introduce `IDataBindableComponent` so any component that needs the data binding stuff, it should implement that interface, this way we will make everything clear

**Pull request closed without merging**
