### PR TITLE
Ability to enable / disable Button

### PR DESCRIPTION
**Pull request by hishamco**
Related to #129, seems the `Enabled` property is already implemented but not checked in razor view

### CODE REVIEW

**Comment by hishamco** [comment]
Seems I need to check all the `ButtonBase` components

**Comment by hishamco** [comment]
@csharpfritz seems the code format action that you added looking for a local branch, so the build is fail

**Comment by csharpfritz** [comment]
It looks like you sent this just after I finished adding it with the work I'm doing to finish the Button component.

I'm investigating the github action, but will decline this merge

**Comment by hishamco** [comment]
> It looks like you sent this just after I finished adding it with the work I'm doing to finish the Button component.

In which PR you did it, coz I created my branch from `dev` and I didn't notice these changes?!!

**Comment by csharpfritz** [comment]
It's still in the ButtonFix branch awaiting merge.

That issue is marked as assigned to me.


Jeff

**Comment by hishamco** [comment]
Ok, it's in your plate then ;)

**Pull request closed without merging**
